package com.ubiqube.etsi.mano.service.vim;

public enum VolumeStatus {
	AVAILABLE, ATTACHING, BACKING_UP, CREATING, DELETING, DOWNLOADING, UPLOADING, ERROR, ERROR_DELETING, ERROR_RESTORING, IN_USE, RESTORING_BACKUP, DETACHING, UNRECOGNIZED, RESERVERD;
}
